export const PACKAGES = [
  {
    id: 1,
    category: "month",
    headTxt: "Basic Package",
    headTxt2: "5,000",
    para: "per month",
    list1: "unlimited Gym Access",
    list2: "2x Fitness Consultant",
    list3: "Nutrition Tracking",
    list4: "1x Free Suplement",
    list5: "3 Days per week",
    list6: "Personal Trainer",
    isBestOffer: false,
  },

  {
    id: 2,
    category: "month",
    headTxt: "Mid Package",
    headTxt2: "10,000",
    para: "per month",
    list1: "unlimited Gym Access",
    list2: "4x Fitness Consultant",
    list3: "Nutrition Tracking",
    list4: "3x Free Suplement",
    list5: "5 Days per week",
    list6: "Personal Trainer",
    isBestOffer: true,
  },
  {
    id: 3,
    category: "month",
    headTxt: "Pro Package",
    headTxt2: "15,000",
    para: "per month",
    list1: "unlimited Gym Access",
    list2: "7x Fitness Consultant",
    list3: "Nutrition Tracking",
    list4: "5x Free Suplement",
    list5: "5 Days per week",
    list6: "Personal Trainer",
    isBestOffer: false,
  },
  {
    id: 4,
    category: "month",
    headTxt: "Athlete Package",
    headTxt2: "20,000",
    para: "per month",
    list1: "unlimited Gym Access",
    list2: "Free Clothes",
    list3: "All Training Program",
    list4: "Free Fitness Consultant",
    list5: "Free Suplement",
    list6: "Gym Cord",
    isBestOffer: false,
  },
  {
    id: 5,
    category: "year",
    headTxt: "Basic Package",
    headTxt2: "50,000",
    para: "per year",
    list1: "unlimited Gym Access",
    list2: "2x Fitness Consultant",
    list3: "Nutrition Tracking",
    list4: "1x Free Suplement",
    list5: "3 Days per week",
    list6: "Personal Trainer",
    isBestOffer: false,
  },

  {
    id: 6,
    category: "year",
    headTxt: "Mid Package",
    headTxt2: "110,000",
    para: "Per year",
    list1: "unlimited Gym Access",
    list2: "4x Fitness Consultant",
    list3: "Nutrition Tracking",
    list4: "3x Free Suplement",
    list5: "5 Days per week",
    list6: "Personal Trainer",
    isBestOffer: true,
  },
  {
    id: 7,
    category: "year",
    headTxt: "Pro Package",
    headTxt2: "170,000",
    para: "per year",
    list1: "unlimited Gym Access",
    list2: "7x Fitness Consultant",
    list3: "Nutrition Tracking",
    list4: "5x Free Suplement",
    list5: "5 Days per week",
    list6: "Personal Trainer",
    isBestOffer: false,
  },
  {
    id: 8,
    category: "year",
    headTxt: "Athlete Package",
    headTxt2: "230,000",
    para: "per year",
    list1: "unlimited Gym Access",
    list2: "Free Clothes",
    list3: "All Training Program",
    list4: "Free Fitness Consultant",
    list5: "Free Suplement",
    list6: "Gym Cord",
    isBestOffer: false,
  },
];
